---
- hosts: addc
  tasks:
    - name: copy over powershell script
      win_copy:
        src: get_domain_available.ps1
        dest: C:\Temp\ad\

    ### install the active directory role
    - name: install AD DS
      win_feature:
        name: AD-Domain-Services
        include_management_tools: true
        include_sub_features: true
        state: present
      register: adds_result

    ### print results of role installation 
    - name: print AD install status
      debug:
        msg: "{{ adds_result }}"

    ### install dns role
    - name: install DNS
      win_feature:
        name: DNS
        include_management_tools: true
        include_sub_features: true
        state: present
      register: dns_result

    ### print results of role installation
    - name: print DNS install status
      debug:
        msg: "{{ dns_result }}"

    ### create a new active directory forest
    - name: create new AD forest
      win_domain:
        dns_domain_name: "{{ domain }}"
        safe_mode_password: "{{ domain_password }}"
      register: create_forest_result

    ### print results of the role installation
    - name: print forest create result
      debug:
        msg: "{{ create_forest_result }}"

    ### the server has to reboot for the changes to take place
    - name: reboot after forest creation
      win_reboot:
      when: create_forest_result.reboot_required
    ###
    - name: wait for system to reboot
      wait_for_connection:
        timeout: 900

    - name: wait for AD to finish installing
      pause:
        minutes: 5

- hosts: vm
  tasks:
  ### set dns ip address
  - name: set DNS ip address
    win_dns_client:
      adapter_names: Ethernet
      ipv4_addresses: "{{ dns_ip }}"

  ### join AD
  - name: join AD
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "administrator@{{domain}}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
    register: domain_result
  - name: print domain status
    debug:
      msg: "{{ domain_result }}"

  ### reboot to apply changes
  - name: reboot after name change
    win_reboot:
    when: domain_result.reboot_required
