---
- hosts: addc
  vars:
    dc_name: "dc01"

  tasks:
    
    - name: change windows hostname
      win_hostname:
        name: "{{ dc_name }}"
      register: new_computer_name_result

    - name: print name change status
      debug:
        msg: "{{ new_computer_name_result }}"
      when: new_computer_name_result is changed

    - name: reboot after name change
      win_reboot:
      when: new_computer_name_result.reboot_required
    
    - name: install AD DS
      win_feature:
        name: AD-Domain-Services
        include_management_tools: true
        include_sub_features: true
        state: present
      register: adds_result

    - name: print AD install status
      debug:
        msg: "{{ adds_result }}"

    - name: install DNS
      win_feature:
        name: DNS
        include_management_tools: true
        include_sub_features: true
        state: present
      register: dns_result

    - name: print DNS install status
      debug:
        msg: "{{ dns_result }}"

    - name: create new AD forest
      win_domain:
        dns_domain_name: "{{ domain }}"
        safe_mode_password: "{{ domain_password }}"
      register: create_forest_result

    - name: print forest create result
      debug:
        msg: "{{ create_forest_result }}"
    
    - name: reboot after forest creation
      win_reboot:
      when: create_forest_result.reboot_required

    - name: wait for system to reboot
      wait_for_connection:
        timeout: 900